# Generated by Django 3.0.8 on 2021-03-31 13:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210211_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
