# Generated by Django 3.0.8 on 2021-04-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20201001_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
    ]
